language: python
sudo: required
before_install:
  - sudo apt-get update -y
services:
  - docker
install:
  # We create a .env file to bypass the initial check done by ./docsearch. If
  # the file is not here, it will ask questions to create the file. We don't
  # need that in CI.
  - touch .env
  - LC_ALL=C
  - DEBIAN_FRONTEND=noninteractive
  - DEBCONF_NONINTERACTIVE_SEEN=true
  - sudo apt-get update -y && sudo apt-get install -yq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update -y && sudo apt-get install -yq curl wget sudo -yq gnupg -yq && curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt-get update -y && sudo apt-get install -yq nodejs -yq
  - sudo apt-get update -y && sudo apt-get install -yq unzip xvfb libxi6 libgconf-2-4 default-jdk

  - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  - echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update -y && sudo apt-get install -yq google-chrome-stable unzip
  - wget -q https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip

  - mv chromedriver /usr/bin/chromedriver
  - chown root:root /usr/bin/chromedriver
  - chmod +x /usr/bin/chromedriver

  - wget -q https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
  - wget -q http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
  - unzip testng-6.8.7.jar.zip

  - npm install -g selenium-standalone@3.0.1 && selenium-standalone install

  - pip install pipenv
  - pipenv install
script:
  - pipenv run ./docsearch test
notifications:
  email: false
  slack:
    secure: e5Xx73XfAMaMwXGrrIjsY6tZ+tcl/IZq/6aKPW/Aw7+Eb4ZO0CnB0XPbUSAvxDMo13/BPbribu5t3JmLH6271ITl8tizveBxOlZjRhs/BIZwHrzVsZoUnirVlxkRvpOxyqQCtqeENA3jglno4boWj3DjI1nwd2ced3NLcOgJsIEFXYj4mhCFtN4cTd7C6Mo6e0NYMrZj6SvXjhUXmWX7ySyfSfu/udAxa0D7YOttsx6g9J/SbxkjW4QETVGOGMueqtZHnsipT0t/NnoKGxiUcS/+vZ/CRTdnysL9udcabdc/4qUp9NidFAqjt1BUb4bak89Uspj/Z+gjHBonb6a7mCWc7Mdt/hdJLXtHy0e0gZq5H6+gF7nnOrUIgo/NysZN8A7tj+68OKultdK63tkN9II1kh/iAgRcE9SExcBE3pGm2BNW2L4ieN6qC12oxeVH+DxFjvxQtObur3uX/MBs4PZrzH8yoRyNDhpP2cEJUHXuEdZBfK5/Trsehe6/772Ezh7Zz2baXUj76HW8M0s+tSK7ewP5OW59zEEaqRGddlBFqxyGKn4FRiSNBaAqdWuzZwYppJ8ivd+hbOHXBb+S08TIdL4RkxXwG1JNcZzMDiJBRySeIiNky4bbShgtsbXT8vpWUgTOyIbIaSm9oFKnUK4qkwjb6expAER4iagdrLA=
