language: python
sudo: required
before_install:
  - sudo apt-get update -y
services:
  - docker
install:
  # We create a .env file to bypass the initial check done by ./docsearch. If
  # the file is not here, it will ask questions to create the file. We don't
  # need that in CI.
  - touch .env
  - LC_ALL=C
  - CHROME_DRIVER_VERSION=`sudo curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - SELENIUM_STANDALONE_VERSION=3.4.0
  - SELENIUM_SUBDIR=$(echo "$SELENIUM_STANDALONE_VERSION" | cut -d"." -f-2)
  # Remove existing downloads and binaries so we can start from scratch.
  - sudo apt-get remove google-chrome-stable
  # Install dependencies.
  - sudo apt-get update
  - sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
  # Install Chrome.
  - sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
  - sudo apt-get -y install google-chrome-stable
  # Install ChromeDriver.
  - sudo wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
  - sudo unzip ~/chromedriver_linux64.zip -d ~/
  - sudo rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod a+x /usr/bin/chromedriver
  # Install Selenium.
  - sudo wget -N http://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
  - sudo mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/bin/selenium-server-standalone.jar
  - sudo chown root:root /usr/bin/selenium-server-standalone.jar
  - sudo chmod 0755 /usr/bin/selenium-server-standalone.jar
  - sudo pip install pipenv
  - sudo pipenv install
  - chromedriver --whitelisted-ips="localhost"
script:
  - pipenv run ./docsearch test
notifications:
  email: false
  slack:
    secure: e5Xx73XfAMaMwXGrrIjsY6tZ+tcl/IZq/6aKPW/Aw7+Eb4ZO0CnB0XPbUSAvxDMo13/BPbribu5t3JmLH6271ITl8tizveBxOlZjRhs/BIZwHrzVsZoUnirVlxkRvpOxyqQCtqeENA3jglno4boWj3DjI1nwd2ced3NLcOgJsIEFXYj4mhCFtN4cTd7C6Mo6e0NYMrZj6SvXjhUXmWX7ySyfSfu/udAxa0D7YOttsx6g9J/SbxkjW4QETVGOGMueqtZHnsipT0t/NnoKGxiUcS/+vZ/CRTdnysL9udcabdc/4qUp9NidFAqjt1BUb4bak89Uspj/Z+gjHBonb6a7mCWc7Mdt/hdJLXtHy0e0gZq5H6+gF7nnOrUIgo/NysZN8A7tj+68OKultdK63tkN9II1kh/iAgRcE9SExcBE3pGm2BNW2L4ieN6qC12oxeVH+DxFjvxQtObur3uX/MBs4PZrzH8yoRyNDhpP2cEJUHXuEdZBfK5/Trsehe6/772Ezh7Zz2baXUj76HW8M0s+tSK7ewP5OW59zEEaqRGddlBFqxyGKn4FRiSNBaAqdWuzZwYppJ8ivd+hbOHXBb+S08TIdL4RkxXwG1JNcZzMDiJBRySeIiNky4bbShgtsbXT8vpWUgTOyIbIaSm9oFKnUK4qkwjb6expAER4iagdrLA=
